### ISSUE TITLE
FIX: Python 2.7.3-3 broken install

### ISSUE THREAD

**Issue by Fetchered** [wahlmanj/atvjailbreak#2]
Fresh ATV 2 jailbreak and install of PlexConnect today. App wouldn't work because, during the 'installatv.bash' process, the script found that the original install method 'wget --no-check-certificate https://yangapp.googlecode.com/files/python_2.7.3-3_iphoneos-arm.deb' produced a 404 error.

I found Yang's newest iphoneos Python branch on github and recommend making this change to the installatv.bash file:

Line 36: wget --no-check-certificate https://github.com/linusyang/python-for-ios/releases/download/v2.7.6-3/python_2.7.6-3_iphoneos-arm.deb; dpkg -i python_2.7.6-3_iphoneos-arm.deb; rm -R python_2.7.6-3_iphoneos-arm.deb

Cheers

**Comment by wahlmanj** [comment]
Updated script
